#!/usr/bin/env bash

KMDBA_KUBECTL="${KMDBA_KUBECTL:-kubectl}"
KMDBA_NAMESPACE="${KMDBA_NAMESPACE:-default}"

args=("$@")

if [[ "${#args[@]}" -gt 1 ]]; then
  if [[ "${args[-2]}" =~ ^(-n|--namespace)$ ]]; then
    "${KMDBA_KUBECTL}" get namespaces --output go-template='{{ range .items }}{{ .metadata.name }}{{"\n"}}{{ end }}'
    echo :4
    exit
  fi
fi

if [[ "${args[-1]}" =~ ^-.* ]]; then
  cat << EOF
-h	show this message
-v	show plugin version
-n	set namespace scope
-f	ignore primary index mismatch
-p	port for backup stream
-t	parallel threads for datafiles transfer
-s	recreate step to start from
--help	show this message
--version	show plugin version
--namespace	set namespace scope
--force	ignore primary index mismatch
--port	port for backup stream
--threads	parallel threads for datafiles transfer
--step	recreate step to start from
EOF
  exit
fi

command=$(printf "%s\n" "${args[@]}" | awk '/^(ls|status|suspend|unsuspend|enter|sql|proc|du|top|repl|prom|recreate)$/ {print; exit}')

if [[ -z "${command}" ]]; then
  cat << EOF
ls	list mariadbs with their pods
status	check mariadb status
suspend	pause mariadb reconciliation
unsuspend	resume mariadb reconciliation
enter	exec into pod
sql	launch mariadb shell
proc	print processlist
du	calculate database disk usage
top	display cpu and ram usage
repl	check replication status
prom	promote replica to primary
recreate	recreate replica from primary
EOF
  exit
fi

namespace=$(printf "%s\n" "${args[@]}" | awk '/^(-n|--namespace)$/ {getline; print; exit}')

case "${command}" in
  ls|status|suspend|unsuspend)
    "${KMDBA_KUBECTL}" --namespace "${namespace:-${KMDBA_NAMESPACE}}" get mariadbs \
      --output go-template='{{ range .items }}{{ .metadata.name }}{{"\n"}}{{ end }}'
  ;;
  enter|sql|proc|du|top)
    "${KMDBA_KUBECTL}" --namespace "${namespace:-${KMDBA_NAMESPACE}}" get pods \
      --selector app.kubernetes.io/name=mariadb \
      --output go-template='{{ range .items }}{{ .metadata.name }}{{"\n"}}{{ end }}'
  ;;
  repl|prom|recreate)
    "${KMDBA_KUBECTL}" --namespace "${namespace:-${KMDBA_NAMESPACE}}" get pods \
      --selector app.kubernetes.io/name=mariadb --selector k8s.mariadb.com/role=replica \
      --output go-template='{{ range .items }}{{ .metadata.name }}{{"\n"}}{{ end }}'
  ;;
esac
echo :4
