#!/usr/bin/env bash

# kubectl-mdba is a kubectl plugin that helps manage
# mariadb-operator semi-sync replication clusters

[[ -n "${DEBUG}" ]] && set -x
set -eo pipefail

VERSION="0.0.9"
OPERATOR_VERSION="0.38.0"

KMDBA_KUBECTL="${KMDBA_KUBECTL:-kubectl}"
KMDBA_NAMESPACE="${KMDBA_NAMESPACE:-default}"

KMDBA_BACKUP_DIR="${KMDBA_BACKUP_DIR:-/var/lib/mysql/.kmdba_backup}"
KMDBA_RESTORE_DIR="${KMDBA_RESTORE_DIR:-/var/lib/mysql/.kmdba_restore}"

KMDBA_IGNORE_PRIMARY_MISMATCH="${KMDBA_IGNORE_PRIMARY_MISMATCH:-0}"
KMDBA_STREAM_PORT="${KMDBA_STREAM_PORT:-4444}"
KMDBA_BACKUP_THREADS="${KMDBA_BACKUP_THREADS:-1}"
KMDBA_RECREATE_STEP="${KMDBA_RECREATE_STEP:-1}"

# colors
RED=$(tput setaf 1)
GRN=$(tput setaf 2)
YLW=$(tput setaf 3)
BLU=$(tput setaf 4)
CYA=$(tput setaf 5)
MAG=$(tput setaf 6)
RES=$(tput sgr0)

### show help message and exit
# arg: none
show_help() {
  cat << EOF | colorize "man"
kubectl mdba helps manage mariadb-operator semi-sync replication clusters

Usage:
  kubectl mdba <command> [<target>]

Commands:
$(awk '/^####/ {$1=""; print}' "$0" \
  | while IFS="-" read -r cmd description; do
      printf " %-26s%s\n" "${cmd}" "${description}"
    done
)

Flags:
  -h, --help                show this message
  -v, --version             show plugin version
  -n, --namespace <ns>      set namespace scope

Recreate Flags:
  -f, --force               ignore primary index mismatch
  -p, --port <num>          port for backup stream (default: ${KMDBA_STREAM_PORT})
  -t, --threads <num>       parallel threads {1..8} for datafiles transfer (default: ${KMDBA_BACKUP_THREADS})
  -s, --step <num>          step {1..14} to start from (default: ${KMDBA_RECREATE_STEP})
EOF
  exit 0
}

### show version and exit
# arg: none
show_version() {
  echo "kubectl mdba version v${VERSION}"
  echo "for mariadb-operator version v${OPERATOR_VERSION}"
  exit 0
}

### validate crucial global vars
# arg: none
check_globals() {
  [[ "${KMDBA_BACKUP_THREADS}" =~ ^[1-8]$ ]] || err "KMDBA_BACKUP_THREADS is not allowed integer {1..8}: ${KMDBA_BACKUP_THREADS}"
  [[ "${KMDBA_IGNORE_PRIMARY_MISMATCH}" =~ ^(0|1)$ ]] || err "KMDBA_IGNORE_PRIMARY_MISMATCH is not allowed integer {0..1}: ${KMDBA_IGNORE_PRIMARY_MISMATCH}"
  [[ "${KMDBA_RECREATE_STEP}" =~ ^([1-9]|1[0-4])$ ]] || err "KMDBA_RECREATE_STEP is not allowed integer {1..14}: ${KMDBA_RECREATE_STEP}"

  if [[ "${KMDBA_RECREATE_STEP}" -ge 8 ]] && [[ "${KMDBA_RECREATE_STEP}" -le 12 ]]; then
    [[ -n "${KMDBA_GTID}" ]] || err "KMDBA_GTID is not set, but it is required because of KMDBA_RECREATE_STEP=${KMDBA_RECREATE_STEP}"
  fi

  [[ "${KMDBA_STREAM_PORT}" =~ ^[0-9]+$ \
    && "${KMDBA_STREAM_PORT}" -ne 3306 \
    && "${KMDBA_STREAM_PORT}" -gt 1024 \
    && "${KMDBA_STREAM_PORT}" -le 65535 ]] || err "KMDBA_STREAM_PORT is not allowed integer {1024..65535}: ${KMDBA_STREAM_PORT}"

  [[ "${KMDBA_BACKUP_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDBA_BACKUP_DIR is not within /var/lib/mysql/: ${KMDBA_BACKUP_DIR}"
  [[ "${KMDBA_RESTORE_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDBA_RESTORE_DIR is not within /var/lib/mysql/: ${KMDBA_RESTORE_DIR}"
}

### ensure that core dependencies are installed
# arg: none
check_dependencies() {
  hash jq 2>/dev/null || err "dependency 'https://github.com/jqlang/jq' is not available"
  hash "${KMDBA_KUBECTL}" 2>/dev/null || err "dependency '${KMDBA_KUBECTL}' is not available"
}

### colorize the input based on the given linter format
# arg: $1 - linter format
colorize() {
  local format

  format="$1"; shift

  if hash bat 2>/dev/null; then
    bat -pp --force-colorization --language "${format}"
  else
    cat
  fi
}

### highlight the message with the given color
# arg: $1 - color
#      $2 - message
highlight() {
  local color message

  color="$1"; shift
  message="$1"; shift

  echo -e "${color}${message}${RES}"
}

### show error message and exit
# arg: $1 - message
err() {
  local message

  message="$1"; shift

  echo "$(highlight "${RED}" "🮲 error:") ${message}" >&2
  exit 1
}

### show a message that denotes the start of a step in a multi-stage task
# arg: $1 - step number
#      $2 - resource role
#      $3 - resource name
#      $4 - message
step() {
  local step role name message

  step="$1"; shift
  role="$1"; shift
  name="$1"; shift
  message="$1"; shift

  case "${role}" in
    primary) role=$(highlight "${GRN}" "${role}") ;;
    replica) role=$(highlight "${YLW}" "${role}") ;;
    cluster) role=$(highlight "${BLU}" "${role}") ;;
  esac

  echo "[$(highlight "${MAG}" "${step}/14")] [$(date +%T)] [${role}] [${name}] ${message}"
}

### ask for confirmation to proceed
# arg: $1 - message
confirm() {
  local message confirm

  message="$1"; shift

  echo -n "$(highlight "${BLU}" "⦿ confirm:") type 'yes' to ${message}: "
  read -r confirm
  [[ "${confirm}" == "yes" ]] || err "confirmation failed"
}

### parse and validate the input
# arg: $@ - arguments
# set: KMDBA_CMD, KMDBA_TARGET, KMDBA_NAMESPACE, KMDBA_IGNORE_PRIMARY_MISMATCH,
#      KMDBA_STREAM_PORT, KMDBA_BACKUP_THREADS, KMDBA_RECREATE_STEP
parse_input() {
  while (( "$#" )); do
    case "$1" in
      -n|--namespace)
        if [[ -n "$2" ]] && [[ "${2:0:1}" != "-" ]]; then
          KMDBA_NAMESPACE="$2"; shift 2
        else
          err "option $1 requires an argument"
        fi
        ;;
      -f|--force)
        KMDBA_IGNORE_PRIMARY_MISMATCH=1; shift
        ;;
      -p|--port)
        if [[ -n "$2" ]] && [[ "${2:0:1}" != "-" ]]; then
          KMDBA_STREAM_PORT="$2"; shift 2
        else
          err "option $1 requires an argument"
        fi
        ;;
      -t|--threads)
        if [[ -n "$2" ]] && [[ "${2:0:1}" != "-" ]]; then
          KMDBA_BACKUP_THREADS="$2"; shift 2
        else
          err "option $1 requires an argument"
        fi
        ;;
      -s|--step)
        if [[ -n "$2" ]] && [[ "${2:0:1}" != "-" ]]; then
          KMDBA_RECREATE_STEP="$2"; shift 2
        else
          err "option $1 requires an argument"
        fi
        ;;
      -v|--version)
        show_version
        ;;
      -h|--help)
        show_help
        ;;
      -*)
        err "invalid option: $1"
        ;;
      *)
        if [[ -z "${KMDBA_CMD}" ]]; then
          case "$1" in
            ls|status|suspend|unsuspend|enter|sql|proc|du|top|repl|prom|recreate)
              KMDBA_CMD="$1"; shift
              ;;
            *)
              err "invalid command: $1"
              ;;
          esac
        else
          if [[ -z "${KMDBA_TARGET}" ]]; then
            KMDBA_TARGET="$1"; shift
          else
            err "multiple targets provided"
          fi
        fi
        ;;
    esac
  done
  [[ -n "${KMDBA_CMD}" ]] || show_help
  [[ -n "${KMDBA_TARGET}" || "${KMDBA_CMD}" =~ ^(ls|top)$ ]] || err "no target provided"
}

### get pod json object and set crucial pod vars
# arg: $1 - pod
# set: POD, POD_IP
get_pod() {
  local pod

  pod="$1"; shift

  POD=$("${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get pod "${pod}" --ignore-not-found --output json)
  [[ -n "${POD}" ]] || err "pod '${pod}' not found in '${KMDBA_NAMESPACE}' namespace"

  jq --exit-status '.metadata.labels["app.kubernetes.io/name"] == "mariadb"' <<< "${POD}" >/dev/null \
    || err "pod '${pod}' in '${KMDBA_NAMESPACE}' namespace is not a mariadb pod"

  POD_IP=$(jq --raw-output '.status.podIP' <<< "${POD}")
}

### get mariadb json object and set crucial mariadb vars
# arg: $1 - mariadb
# set: MARIADB, MARIADB_REPLICATION, MARIADB_SUSPEND, MARIADB_CURRENT_PRIMARY_INDEX, MARIADB_DESIRED_PRIMARY_INDEX
get_mariadb() {
  local mariadb

  mariadb="$1"; shift

  MARIADB=$("${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get mariadb "${mariadb}" --ignore-not-found --output json)
  [[ -n "${MARIADB}" ]] || err "mariadb '${mariadb}' not found in '${KMDBA_NAMESPACE}' namespace"

  MARIADB_REPLICATION=$(jq --raw-output '.spec.replication.enabled' <<< "${MARIADB}")
  MARIADB_SUSPEND=$(jq --raw-output '.spec.suspend' <<< "${MARIADB}")
  MARIADB_CURRENT_PRIMARY_INDEX=$(jq --raw-output '.status.currentPrimaryPodIndex' <<< "${MARIADB}")
  MARIADB_DESIRED_PRIMARY_INDEX=$(jq --raw-output '.spec.replication.primary.podIndex' <<< "${MARIADB}")
}

### assert that semi-sync replication is enabled
# arg: none
assert_replication_enabled() {
  local mariadb

  mariadb="${KMDBA_TARGET}"

  [[ "${MARIADB_REPLICATION}" == "true" ]] || err "semi-sync replication is disabled for mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
}

### check if mariadb is suspended
# arg: none
is_suspended() {
  if [[ "${MARIADB_SUSPEND}" == "true" ]]; then
    return 0
  else
    return 1
  fi
}

### check if desired and current primary indexes are equal
# arg: none
is_primary_index_mismatched() {
  if [[ "${MARIADB_DESIRED_PRIMARY_INDEX}" -ne "${MARIADB_CURRENT_PRIMARY_INDEX}" ]]; then
    if (( KMDBA_IGNORE_PRIMARY_MISMATCH )); then
      confirm "ignore mismatched desired '${MARIADB_DESIRED_PRIMARY_INDEX}' and current '${MARIADB_CURRENT_PRIMARY_INDEX}' primary pod indexes"
      return
    fi
    err "aborted due to mismatched desired '${MARIADB_DESIRED_PRIMARY_INDEX}' and current '${MARIADB_CURRENT_PRIMARY_INDEX}' primary pod indexes"
  fi
}

### check if pod is a replica
# arg: $1 - pod
is_replica() {
  local pod pod_index

  pod="$1"; shift

  pod_index="${pod##*-}"

  if [[ "${pod_index}" -eq "${MARIADB_CURRENT_PRIMARY_INDEX}" ]]; then
    err "pod '${pod}' in '${KMDBA_NAMESPACE}' namespace is not a replica"
  fi
}

### run a shell command in a mariadb pod
# arg: $1 - pod
#      $2 - command
exec_pod() {
  local pod command

  pod="$1"; shift
  command=("$@"); shift "$#"

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" exec "${pod}" --container mariadb -- "${command[@]}"
}

### run an interactive shell command in a mariadb pod
# arg: $1 - pod
#      $2 - command
exec_pod_it() {
  local pod command

  pod="$1"; shift
  command=("$@"); shift "$#"

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" exec "${pod}" --stdin --tty --container mariadb -- "${command[@]}"
}

### run a sql query in a mariadb pod
# arg: $2 - pod
#      $2 - sql query
run_sql_query() {
  local pod sql_query

  pod="$1"; shift
  sql_query="$1"; shift

  exec_pod "${pod}" bash -c "mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --execute='${sql_query}'"
}

### suspend mariadb reconciliation
# arg: $1 - mariadb
suspend_mariadb() {
  local mariadb

  mariadb="$1"; shift

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
    --patch='[{"op": "replace", "path": "/spec/suspend", "value": true}]' \
      || err "failed to suspend mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
}

### suspend mariadb reconciliation
# arg: $1 - mariadb
unsuspend_mariadb() {
  local mariadb

  mariadb="$1"; shift

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
    --patch='[{"op": "replace", "path": "/spec/suspend", "value": false}]' \
      || err "failed to unsuspend mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
}

#============================================#
#==========| SUBCOMMAND FUNCTIONS |==========#
#============================================#

#### ls [<mariadb>] - list mariadbs with their pods
# arg: none
mdba_ls() {
  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get mariadbs --ignore-not-found \
    | awk "NR == 1 || \$1 ~ /${KMDBA_TARGET:-.}/" \
    | colorize "VimHelp"
  echo
  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get pods --selector app.kubernetes.io/name=mariadb --ignore-not-found --output wide \
    | awk "NR == 1 || \$1 ~ /${KMDBA_TARGET:-.}/" \
    | colorize "VimHelp"
}

#### status <mariadb> - check mariadb status
# arg: none
mdba_status() {
  local mariadb yq_option

  mariadb="${KMDBA_TARGET}"

  get_mariadb "${mariadb}"

  if hash yq 2>/dev/null; then
    yq_option=$(yq --version | grep --quiet "mikefarah" && echo "--prettyPrint" || echo "--yaml-output")
    yq "${yq_option}" '.spec.replication.primary * .status' <<< "${MARIADB}" | colorize "yaml"
  else
    jq --raw-output '.spec.replication.primary * .status' <<< "${MARIADB}"
  fi
}

#### suspend <mariadb> - pause mariadb reconciliation
# arg: none
mdba_suspend() {
  local mariadb

  mariadb="${KMDBA_TARGET}"

  get_mariadb "${mariadb}"

  if ! is_suspended; then
    suspend_mariadb "${mariadb}"
  else
    err "mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace is already suspended"
  fi
}

#### unsuspend <mariadb> - resume mariadb reconciliation
# arg: none
mdba_unsuspend() {
  local mariadb

  mariadb="${KMDBA_TARGET}"

  get_mariadb "${mariadb}"

  if is_suspended; then
    unsuspend_mariadb "${mariadb}"
  else
    err "mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace is not suspended"
  fi
}

#### enter <pod> - exec into pod
# arg: none
mdba_enter() {
  local pod

  pod="${KMDBA_TARGET}"

  get_pod "${pod}"
  exec_pod_it "${pod}" "bash"
}

#### sql <pod> - launch mariadb shell
# arg: none
mdba_sql() {
  local pod

  pod="${KMDBA_TARGET}"

  get_pod "${pod}"
  exec_pod_it "${pod}" bash -c "mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD}"
}

#### proc <pod> - print processlist
# arg: none
mdba_proc() {
  local pod

  pod="${KMDBA_TARGET}"

  get_pod "${pod}"
  run_sql_query "${pod}" 'SHOW PROCESSLIST;'
}

#### du <pod> - calculate database disk usage
# arg: none
mdba_du() {
  local pod

  pod="${KMDBA_TARGET}"

  get_pod "${pod}"
  exec_pod "${pod}" bash -o pipefail -c "find /var/lib/mysql/ -maxdepth 1 -type d ! -name 'lost+found' -exec du --summarize --human-readable {} \; | sort --reverse --human-numeric-sort | awk --field-separator=/ '{print \$1, \$5}'"
}

#### top [<pod>] - display cpu and ram usage
# arg: none
mdba_top() {
  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" top pods --selector app.kubernetes.io/name=mariadb --containers \
    | sed 's/(cores)\|(bytes)//g' \
    | column -t \
    | awk "NR == 1 || \$1 ~ /${KMDBA_TARGET:-.}/" \
    | colorize "VimHelp"
}

#### repl <replica> - check replication status
# arg: none
mdba_repl() {
  local replica mariadb

  replica="${KMDBA_TARGET}"
  mariadb="${KMDBA_TARGET%-[0-9]}"

  get_pod "${replica}"
  get_mariadb "${mariadb}"

  assert_replication_enabled
  is_replica "${replica}"

  run_sql_query "${replica}" 'SHOW VARIABLES LIKE "rpl_semi_sync_slave_enabled";' \
    | grep --quiet ON || err "semi-sync replication is disabled on this pod"
  run_sql_query "${replica}" 'SHOW SLAVE STATUS\G' \
    | awk '/Master_Host|Seconds_Behind_Master|Slave_IO|Slave_SQL|Last_IO_Error|Last_SQL_Error/ {$1=$1; print}' \
    | sort \
    | colorize "yaml"
}

#### prom <replica> - promote replica to primary
# arg: none
mdba_prom() {
  local replica mariadb replica_index

  replica="${KMDBA_TARGET}"
  mariadb="${replica%-[0-9]}"
  replica_index="${replica##*-}"

  get_pod "${replica}"
  get_mariadb "${mariadb}"

  assert_replication_enabled
  is_replica "${replica}"
  is_primary_index_mismatched

  confirm "promote replica pod '${replica}' in '${KMDBA_NAMESPACE}' namespace to primary"

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
    --patch='[{"op": "replace", "path": "/spec/replication/primary/podIndex", "value": '"${replica_index}"'}]'

  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" wait mariadb "${mariadb}" --timeout=1m \
    --for jsonpath='{.status.currentPrimary}'="${replica}" \
      || err "pod ${replica} from mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace is not primary yet"
}

#### recreate <replica> - recreate replica from primary
# arg: none
mdba_recreate() {
  local replica mariadb replica_ip primary log_file
  local -i step_num=1

  replica="${KMDBA_TARGET}"
  mariadb="${replica%-[0-9]}"

  get_pod "${replica}"
  get_mariadb "${mariadb}"

  assert_replication_enabled
  is_replica "${replica}"
  is_primary_index_mismatched

  replica_ip="${POD_IP}"
  primary="${mariadb}-${MARIADB_CURRENT_PRIMARY_INDEX}"

  get_pod "${primary}"

  confirm "recreate replica pod '${replica}' in '${KMDBA_NAMESPACE}' namespace from primary pod '${primary}'"

  log_file=$(mktemp)
  echo "$(highlight "${CYA}" "⦿ log:") ${log_file}"

  {

  # step 1
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Looking for leftovers from previous attempts"
    exec_pod "${replica}" bash -c "test ! -e ${KMDBA_BACKUP_DIR}" \
      || err "please remove '${KMDBA_BACKUP_DIR}' directory in the pod"
    exec_pod "${replica}" bash -c "test ! -e ${KMDBA_RESTORE_DIR}" \
      || err "please remove '${KMDBA_RESTORE_DIR}' directory in the pod"
    exec_pod "${replica}" bash -c "test ! \$(pgrep socat)" \
      || err "please kill 'socat' process running in the pod"
  fi
  (( step_num +=1 ))

  # step 2
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "cluster" "${mariadb}" "Pausing reconciliation by mariadb-operator"
    if ! is_suspended; then
      suspend_mariadb "${mariadb}"
    fi
  fi
  (( step_num +=1 ))

  # step 3
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Dropping databases to free up disk space"
    exec_pod "${replica}" bash -o pipefail -c "mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --batch --skip-column-names --execute='SHOW DATABASES WHERE Database NOT IN (\"information_schema\", \"performance_schema\", \"mysql\", \"sys\");' \
      | xargs --no-run-if-empty --replace mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --execute='DROP DATABASE \`{}\`;'" \
      || err "failed to drop databases"
  fi
  (( step_num +=1 ))

  # step 4
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Preparing to receive the backup stream from primary '${primary}'"
    exec_pod_it "${replica}" nohup bash -o pipefail -c "mkdir --parents ${KMDBA_BACKUP_DIR} && socat -u TCP-LISTEN:${KMDBA_STREAM_PORT},reuseaddr stdio | mbstream --parallel=${KMDBA_BACKUP_THREADS} --extract --directory=${KMDBA_BACKUP_DIR} &" \
      || err "failed to create the receiver pipeline"
  fi
  (( step_num +=1 ))

  # step 5
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "primary" "${primary}" "Starting the backup stream to replica '${replica}:${KMDBA_STREAM_PORT}:${KMDBA_BACKUP_DIR}'"
    exec_pod "${primary}" nohup bash -o pipefail -c "mariadb-backup --parallel=${KMDBA_BACKUP_THREADS} --skip-ssl --backup --user=root --password=\${MARIADB_ROOT_PASSWORD} --stream=xbstream | socat -u stdio TCP:${replica_ip}:${KMDBA_STREAM_PORT}" \
      || err "backup stream has failed"
  fi
  (( step_num +=1 ))

  # step 6
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Preparing the backup in '${KMDBA_BACKUP_DIR}'"
    exec_pod "${replica}" bash -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --prepare" \
      || err "failed to prepare the backup"
  fi
  (( step_num +=1 ))

  # step 7
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Retrieving the last change GTID"
    KMDBA_GTID=$(exec_pod "${replica}" bash -c "awk '{print \$NF}' ${KMDBA_BACKUP_DIR}/mariadb_backup_binlog_info") \
      || err "failed to retrieve the last change GTID"
    [[ -n "${KMDBA_GTID}" ]] || err "failed to retrieve the last change GTID"
  fi
  (( step_num +=1 ))

  # step 8
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Restoring the backup to '${KMDBA_RESTORE_DIR}'"
    exec_pod "${replica}" bash -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --datadir=${KMDBA_RESTORE_DIR} --move-back" \
      || err "failed to restore the backup"
  fi
  (( step_num +=1 ))

  # step 9
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Moving the restored backup from '${KMDBA_RESTORE_DIR}' to '/var/lib/mysql'"
    exec_pod "${replica}" bash -c "rm --recursive --force /var/lib/mysql/*; mv ${KMDBA_RESTORE_DIR}/* /var/lib/mysql" \
      || err "failed to move the restored backup"
  fi
  (( step_num +=1 ))

  # step 10
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Removing temporary directories '${KMDBA_BACKUP_DIR}' and '${KMDBA_RESTORE_DIR}'"
    exec_pod "${replica}" bash -c "rm --recursive --force ${KMDBA_BACKUP_DIR} ${KMDBA_RESTORE_DIR}" \
      || err "failed to remove temporary directories"
  fi
  (( step_num +=1 ))

  # step 11
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Recreating the pod"
    "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" delete pod "${replica}" \
      || err "failed to delete the pod"
    "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" wait --for condition=ready pod "${replica}" --timeout=3m \
      || err "the new pod failed to become ready"
  fi
  (( step_num +=1 ))

  # step 12
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Setting the last change GTID"
    run_sql_query "${replica}" "RESET SLAVE ALL; SET GLOBAL gtid_slave_pos = \`${KMDBA_GTID}\`;" \
      || err "failed to set the last change GTID"
  fi
  (( step_num +=1 ))

  # step 13
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "cluster" "${mariadb}" "Resuming reconciliation by mariadb-operator"
    unsuspend_mariadb "${mariadb}"
  fi
  (( step_num +=1 ))

  # allow mariadb-operator to reconcile replication
  sleep 15

  # step 14
  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
    step "${step_num}" "replica" "${replica}" "Checking replication status"
    mdba_repl
  fi

  } 2>&1 | tee "${log_file}"

  echo "$(highlight "${CYA}" "⦿ log:") ${log_file}"
}

main() {
  parse_input "$@"
  check_globals
  check_dependencies

  case "${KMDBA_CMD}" in
    ls)        mdba_ls        ;;
    status)    mdba_status    ;;
    suspend)   mdba_suspend   ;;
    unsuspend) mdba_unsuspend ;;
    enter)     mdba_enter     ;;
    sql)       mdba_sql       ;;
    proc)      mdba_proc      ;;
    du)        mdba_du        ;;
    top)       mdba_top       ;;
    repl)      mdba_repl      ;;
    prom)      mdba_prom      ;;
    recreate)  mdba_recreate  ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
